live_config_reload = true
working_directory = "None"

# Themes
import = [
  "~/.config/alacritty/gruvbox_dark.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/keybinds.toml"
]

[window]
title = "Alacritty"
decorations = "Full"
blur = true
opacity = 0.95
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 110
lines = 60

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "FiraMono Nerd Font"
normal.style = "Regular"
size = 14.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"
